### PR TITLE
[wip] Add binding to grabCut

### PR DESCRIPTION
**Pull request by timjb**
An example is missing because of #31.

Warning: The code is not tested. Please don't merge yet.

### CODE REVIEW

**Comment by basvandijk** [comment]
@timjb Note that I just renamed `src/OpenCV/ImgProc/MiscImgTransform.hsc` to `src/OpenCV/ImgProc/MiscImgTransform.hs`.  You should now put hsc2hs pragma's like:

```
#num GC_INIT_WITH_RECT
#num GC_INIT_WITH_MASK
#num GC_EVAL
```

in `OpenCV.Internal.ImgProc.MiscImgTransform`.

**Comment by timjb** [comment]
@basvandijk I've rebased the PR onto the current master branch.

Warning: The code is still not tested. Please don't merge yet.

**Comment by basvandijk** [comment]
Hi @timjb, any chance you can finish testing this so I can merge it?

BTW are you going to ZuriHac 2017? Would be cool to meet you there again!

**Comment by timjb** [comment]
Hey @basvandijk! I had completely forgotten this pull request. Thanks for the reminder! I will take a look at this next weekend.

I'm not going to ZuriHac 2017. Maybe next year!

**Comment by timjb** [comment]
I've got it working and added an example:

grabcutbird

**Comment by basvandijk** [comment]
Very cool! Thanks a lot.

**Pull request merged**
