### PR TITLE
Generate Matx51f / Matx51d.

### PR DESCRIPTION
**Pull request by rehno-lindeque**
Since OpenCV doesn't have typedefs for these it was a bit awkward to work with Matx51d/Matx51f. Does this look ok?

### CODE REVIEW

**Comment by roelvandijk** [comment]
Hi Rehno, looks ok to me!

It appears that the typedefs are re-used. Could you place them in an include file so the definitions can be shared? 

```haskell
C.include "custom_typedefs.hpp"
```

I made up the `custom_typedefs.hpp` name. Other ideas are also welcome. The file should be placed in the `include` directory.

This would also make it easier to add other typedefs in the future.

**Comment by rehno-lindeque** [comment]
Thanks Roel! How about one of these?

* `opencv_typedefs.hpp`
* `opencv_custom_typedefs.hpp` 
* `opencv_extra_typedefs.hpp` 
* `opencv_matx_typedefs.hpp` 
* `matx_typedefs.hpp`

I see there's already typedefs in some of the files under `include/`. Since these typedefs have to be injected into the `cv` namespace, perhaps it makes sense to isolate them somewhat.

**Comment by roelvandijk** [comment]
Good point about isolating the typedefs. I am not really happy with our existing include files. When writing include directives it is not really clear where the files are coming from.

How about we prefix haskell opencv includes with `haskell_opencv_`?

I like your `matx_typedefs.hpp` name. So that would become `haskell_opencv_matx_typedefs.hpp`.

**Comment by rehno-lindeque** [comment]
Ok, not sure why travis fails but this seems to work for me. How does this look?

**Comment by roelvandijk** [comment]
Looks good! Merged, thanks!

The travis failure looks to be a dependency problem with the c++ opencv library.

**Pull request merged**
