### PR TITLE
Add a routine for Canny edge detection

### PR DESCRIPTION
**Pull request by ocharles**
Appears to work, the documentation image is generated as expected.

### CODE REVIEW

**Comment by roelvandijk** [comment]
Nice! Works as advertised. 

The [documentation](http://docs.opencv.org/3.0-last-rst/modules/imgproc/doc/feature_detection.html#canny) states that both the input image and the output edge map are 8-bit images. You can encode that by setting the `depth` type parameter of a `Mat` to `Word8`. 

Furthermore, it is implied (by the word 'image') that these matrices are 2 dimensional.  You can constrain the function to only work on 2-dimensional matrices by setting the `shape` type parameter to `'S ['D, 'D]`. Which means there must be 2 dimensions, but we don't know anything about the sizes of these dimensions. I'm not really sure about the shape and would have to check the actual c++ source to see if they place any constraints on the shape.

Thanks for the patch!

**Comment by basvandijk** [comment]
Hi Ollie, nice to have you on board!

@roelvandijk 
> You can constrain the function to only work on 2-dimensional matrices by setting the shape type parameter to 'S ['D, 'D]. Which means there must be 2 dimensions, but we don't know anything about the sizes of these dimensions. 

If we don't know anything about the sizes of these 2 dimensions we should probably make them polymorphic as in: `'S [width, height]`.

**Comment by ocharles** [comment]
Thanks, let me get those changes in now! Is anyone around for a brief chat btw? I'm trying to wrap `findContours` next, but I don't know what should be returned. If anyone can drop on IRC for example, that would be great! I'm `ocharles` on FreeNode, but can chat in other mediums if easier.

**Comment by basvandijk** [comment]
[findContours](http://docs.opencv.org/3.0-last-rst/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html?highlight=findcontours#findcontours) seems like a nice challenge to bind.

From briefly looking at the documentation I would expect the type to be something like this:

```haskell
data Contour = 
     Contour 
     { contour   :: !(V.Vector Point2i)
     , hierarchy :: !Hierarchy
     }

data Hierarchy =
     Hierarchy 
     { nextContour       :: !Int
     , previousContour   :: !Int
     , firstChildContour :: !Int
     , parentContour     :: !Int
     }

findContours 
    :: forall width height point2i
     . (Convert point2i Point2i)
    => Mat ('S [width, height]) (`S 1) Word8
    -> ContourRetrievalMode
    -> ContourApproximationMethod
    -> point2i -- ^ offset
    -> V.Vector Contour
```

I haven't studied the function in detail so I could be way off here...

You could look at [orbDetectAndCompute](https://github.com/LumiGuide/haskell-opencv/blob/34af829c7dfb9f20dc924608d612f7dfc09b1045/src/OpenCV/Features2d.hsc#L225) for how to work with Vectors.

Unfortunately I won't be available for a call or chat today.

**Comment by ocharles** [comment]
Great, that should get me going. That's roughly what I have so far, it's the construction of the Vector that I'm not sure about, because I don't know how many elements to expect. I'll look into the ORB stuff and see if I can get anything from that, thanks!

> Unfortunately I won't be available for a call or chat today.
 
No problem, I'm actually just finishing up here for the day anyway.

**Comment by basvandijk** [comment]
@ocharles I added you as a collaborator of `haskell-opencv`.

I trust you enough not to mess things up ;-).

**Pull request merged**
