### PR TITLE
Expose internals

### PR DESCRIPTION
**Pull request by rehno-lindeque**
It might be helpful to expose C types / internal modules to the outside world while this package is undergoing development.

### CODE REVIEW

**Comment by roelvandijk** [comment]
Yes, this was also asked in #23. I want to do this, but also make it really obvious that you are using internal modules.

It requires a bunch of renaming. I highlighted in bold the names that should be added to the modules listed under `other-modules`:

OpenCV.**Internal**.C.Inline
OpenCV.**Internal**.C.PlacementNew
OpenCV.**Internal**.C.PlacementNew.TH
OpenCV.**Internal**.C.Types
OpenCV.Calib3d.**Internal**.Constants
OpenCV.Core.ArrayOps.Internal
OpenCV.Core.Types.**Internal**.Constants
OpenCV.Core.Types.Internal
OpenCV.Core.Types.Mat.**Internal**.Depth
OpenCV.Core.Types.Mat.Internal
OpenCV.Core.Types.Mat.**Internal**.Marshal
OpenCV.Core.Types.Mat.**Internal**.ToFrom
OpenCV.Core.Types.Matx.Internal
OpenCV.Core.Types.Matx.**Internal**.TH
OpenCV.Core.Types.Point.Internal
OpenCV.Core.Types.Point.**Internal**.TH
OpenCV.Core.Types.Rect.Internal
OpenCV.Core.Types.Rect.**Internal**.TH
OpenCV.Core.Types.Size.Internal
OpenCV.Core.Types.Size.**Internal**.TH
OpenCV.Core.Types.Vec.Internal
OpenCV.Core.Types.Vec..**Internal**TH
OpenCV.Exception.Internal
OpenCV.ImgCodecs.Internal
OpenCV.ImgProc.MiscImgTransform.Internal
OpenCV.ImgProc.Types.Internal
OpenCV.Internal
OpenCV.**Internal**.Mutable

**Comment by rehno-lindeque** [comment]
I've amended this one to rename those modules. How does this look?

**Comment by roelvandijk** [comment]
Big patch :-) I will test locally and rebase if successful.

**Comment by roelvandijk** [comment]
Merged. Thanks!

In the future I might put all internal modules under `OpenCV.Internal` in the hierarchy. But for now this is acceptable.

**Comment by rehno-lindeque** [comment]
Thanks!

**Pull request closed without merging**
