### PR TITLE
WIP (seg fault) - Wrap cv::drawContours

### PR DESCRIPTION
**Pull request by ocharles**
Any idea why this causes a segmentation fault?

If I

a. Comment out the call to `cv::findContours` in the definition of `findContours` the execution completes, though obviously drawing no contours.
b. Comment out the `[CU.exp| void { delete $(Mat * ptr) }|]` in the definition of `FromPtr` for `Mat`, it also works.

It seems that a matrix is getting freed, but the underlying pointer has changed. It only seems to happen in the demo code for `drawContours` - for example the `findContours` test is fine with the `delete`.

### CODE REVIEW

**Comment by basvandijk** [comment]
I just merged `master` into your branch.

I'm also getting the seg fault. Investigating...

**Comment by basvandijk** [comment]
Note that the seg fault disappears when I change the `flower_768x512` to a `lambda` in the `flowerContours` example like: 

```haskell
let edges = exceptError $ canny 30 20 Nothing Nothing lambda
```

I suspect it's a bug in OpenCV. Time to dive in the [source](https://github.com/Itseez/opencv/blob/3.1.0/modules/imgproc/src/contours.cpp#L1704) of `findContours`...

**Comment by ocharles** [comment]
Oh, nice find... That's weird!

**Comment by basvandijk** [comment]
I also tested this with the latest opencv-HEAD (just uncomment the lines in [opencv-default.nix](https://github.com/LumiGuide/haskell-opencv/blob/master/opencv-default.nix) but the segher@kernel.crashing.org fault remains.

**Comment by basvandijk** [comment]
@ocharles  I just merged your PR. The segfault has disappeared. Verly likely because of https://github.com/LumiGuide/haskell-opencv/commit/c15dcab0b38266f9eacf74584ef548287e8eb07f.

**Pull request merged**
