### PR TITLE
Updated local repo with examples dir. Implement resizeWindow function.

### PR DESCRIPTION
**Pull request by Cortlandd**

### CODE REVIEW

**Comment by basvandijk** [comment]
The implementation LGTM. Before I merge this, could you represent this PR as a single commit with a short descriptive name like `Implement the resizeWindow function`? I don't like to have too many merge patches in my history.

Note that you can just do a force push to the branch where you pushed your commits to. There should be no need to create a new PR.

Thanks!

**Comment by Cortlandd** [comment]
Hmm, I think fixed it.

**Comment by roelvandijk** [comment]
You succesfully merged your 2 commits into 1. Could you also rename the commit to something more descriptive? Like "_HighGui: implemented resizeWindow_"

Usually when I implement a new feature I work in a feature branch, like `feat-resize-window`. That way I can quickly try some things and don't care about my commit messages. I usually just have _WIP_, short for work in progress, as the message for every commit. Then, once I'm satisfied I rebase the feature branch onto `master` (or some other branch). During rebase you can both squash commits (combine multiple commits into a single commit) and rename the commits.

**Comment by basvandijk** [comment]
Almost ;-) The only thing left to do is to give your commit the correct name like "Implement the resizeWindow function".

**Comment by Cortlandd** [comment]
I believe its correct now. Thanks guys :smile:

**Comment by roelvandijk** [comment]
Perfect. Thanks!

**Pull request merged**
