### PR TITLE
Add `fastNlMeansDenoisingColored`

### PR DESCRIPTION
**Pull request by tolysz**
Add binding for image denoising using Non-local Means Denoising algorithm 
http://docs.opencv.org/3.1.0/d1/d79/group__photo__denoise.html

### CODE REVIEW

**Comment by tolysz** [comment]
Resolvers above `> nightly-2016-09-14` should be regarded as allowed failures.

**Comment by basvandijk** [comment]
Thanks!

**Comment by tolysz** [comment]
Thank you :)

**Comment by basvandijk** [comment]
Nice [example](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-Photo.html#v:fastNlMeansDenoisingColored).

**Pull request merged**
